# -*- zsh -*-
# (copied from zprezto runcoms)
# Defines environment variables
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# grab any secrets like github tokens or comnpany-specific URLs
source ~/.secrets

GK_DOTFILES=/Users/gknoy/git/personal/dotfiles

# 'bat' options. Not sure if I need
# -F: quit if less than full screen
# export BAT_PAGER='less -RF'
# export BAT_PAGER='less -R'

export PYENV_ROOT="$HOME/.pyenv"
# export PATH="$PYENV_ROOT/bin:$PATH"
export PIPENV_PYTHON="$PYENV_ROOT/shims/python"

