#
# .zshrc - Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

setopt interactive_comments
setopt share_history

# make ctrl-u / cmd-backspace delete only leftward, instead of the whole line
bindkey \^U backward-kill-line

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

plugin=(
  pyenv
)

# --- pyenv initialization, so that it shadows homebrew python/pip
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# --- GK config
source "$GK_DOTFILES/zsh/aliases"
source "$GK_DOTFILES/shell-imports/node.sh"
source "$GK_DOTFILES/shell-imports/python.sh"
source "$GK_DOTFILES/shell-imports/db-dump.sh"
source "$GK_DOTFILES/shell-imports/dev.sh"

# --- add hook to update tab color via printfs for Iterm2 whenever we change dirs
if [[ -n "$ITERM_PROFILE" ]]; then
  source "$GK_DOTFILES/shell-imports/iterm2.sh"
  add-zsh-hook chpwd auto-tab-color
  auto-tab-color  # also run when first initializing shell
fi
